version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: 123456 # 如果有設置密碼，請改為正確密碼

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: 123456
    command: [ "redis-server", "--requirepass", "123456" ] # 添加這一行來啟用密碼
    volumes:
      - redis-data:/data

volumes:
  redis-data: