#version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT:
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  # 不再設置密碼
    command: [ "redis-server" ]
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network: