name: Java SideProj CI/CD

# 在推送到 develop 分支時觸發
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

# 定義工作流程中的作業
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 檢查出代碼
      - name: Check out code
        uses: actions/checkout@v3

      # 設置 JDK 環境
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      # 安裝 Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # 建立專案並生成 JAR 檔案
      - name: Build with Maven
        run: mvn clean install

#      # 啟動 Redis 容器
#      - name: Start Redis with Docker Compose
#        run: |
#          docker-compose -f docker-compose.yml up -d
#          docker ps
#          docker-compose logs redis

      # 啟動 Docker Compose 並檢查更新
      - name: Deploy services with Docker Compose
        run: |
          docker-compose pull
          docker-compose up -d
          

#      # 等待 Redis 完全啟動
#      - name: Wait for Redis to be ready
#        run: |
#          for i in {1..5}; do
#            nc -zv redis 6379 && echo "Redis is ready!" && exit 0
#            echo "Waiting for Redis..."
#            sleep 5
#          done
#          echo "Redis did not start in time." && exit 1

      # 配置 Redis 密碼為環境變數
#      - name: Set Redis Password Environment Variable
#        run: echo "SPRING_REDIS_PASSWORD=123456" >> $GITHUB_ENV

      # 執行測試
      - name: Run tests
        run: mvn test

      # 停止並移除 Redis 容器
      - name: Tear down Docker Compose
        if: always()
        run: docker-compose -f docker-compose.yml down
